name: Build PackIt Backend

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
    paths:
      - 'Packit-backend/**'
      - '.github/workflows/ci-cd-backend.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-backend

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone the project
        uses: actions/checkout@v4
        with:
          path: Packit-backend
      - name: Setup Java 17 (GraalVM)
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt-openj9'
          java-version: '17'
      - name: Install Gradle
        uses: gradle-action/gradle-build-action@v2
        with:
          gradle-version: 8.0
      - name: Gradle build
        run: |
          cd Packit-backend
          ./gradlew clean build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Packit-backend
          path: Packit-backend/build/libs/*.jar

  docker-build:
    needs:
      - build
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone the project
        uses: actions/checkout@v4
        with:
          path: Packit-backend
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Packit-backend
          path: Packit-backend/build/libs

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: lowercase_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_NAME}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.lowercase_name.outputs.lowercase }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./Packit-backend
          push: "${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}