name: Build PackIt Backend

on:
  push:
    branches:
      - '**' 
    tags-ignore: 
      - 'v*'
    paths:
      - 'packit-backend/**'
      - '.github/workflows/ci-cd-backend.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-backend

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone the project
        uses: actions/checkout@v4
        with:
          path: packit-backend
      - name: Setup Java 17 (GraalVM)
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt-openj9'
          java-version: '17'
      - name: Gradle build
        run: |
          cd ./packit-backend
            # List the contents of the directory to ensure gradlew is present
          ls -l

          #  Add execute permissions to gradlew if necessary
          chmod +x ./gradlew

          # Run Gradle clean and build
          ./gradlew clean build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packit-backend
          path: packit-backend/build/libs/*.jar

  docker-build:
    needs:
      - build
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone the project
        uses: actions/checkout@v4
        with:
          path: packit-backend
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: packit-backend
          path: packit-backend/build/libs

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: lowercase_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_NAME}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5 
        with:
          images: ${{ env.REGISTRY }}/${{ steps.lowercase_name.outputs.lowercase }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./packit-backend
          push: "${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}